apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: vault-provider-config
spec:
  address: http://127.0.0.1:8200
  # Test Token. Do not check real tokens into Git
  token: "hvs.gWLTHMayCJ5FrNhTix684Bly"
  # The credentials below are not used until a refactor
  credentials:
    source: Secret
    secretRef:
      name: vault-creds
      namespace: vault
      key: credentials
