apiVersion: generic.vault.upbound.io/v1alpha1
kind: Secret
metadata:
  name: vault-creds
spec:
  forProvider:
    path: "generic/vault-creds"
    dataJsonSecretRef:
      name: vault-creds
      namespace: vault
      key: credentials
  providerConfigRef:
    name: vault-provider-config
