apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  name: generic-secret-mount
spec:
  deletionPolicy: Delete
  forProvider:
    path: "generic"
    type: "generic"
  providerConfigRef:
    name: vault-provider-config
