apiVersion: kv.vault.upbound.io/v1alpha1
kind: SecretV2
metadata:
  name: vault-creds
spec:
  forProvider:
    mount: "kvv2"
    name: "vault-creds"
    cas: 1
    customMetadata:
      - maxVersions: 99
        deleteVersionAfter: 6000
    dataJsonSecretRef:
      name: vault-creds
      namespace: vault
      key: credentials
  providerConfigRef:
    name: vault-provider-config
